# Generated by Django 4.1.3 on 2022-11-13 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_categories_listing_watchlist_comments_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=256,
                verbose_name="Comment",
            ),
            preserve_default=False,
        ),
    ]
